# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ray007330"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/rayzhang007330/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/ray.zhang.50/"

[social.params]
icon = "brand-facebook"

[[social]]
identifier = "instagram"
name = "instagram"
url = "https://www.instagram.com/ray_zhang.___/"

[social.params]
icon = "brand-instagram"